/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bookmarks`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/interactive`; params?: Router.UnknownInputParams; } | { pathname: `/menu`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/articles/concepts`; params?: Router.UnknownInputParams; } | { pathname: `/articles/method`; params?: Router.UnknownInputParams; } | { pathname: `/articles/rules`; params?: Router.UnknownInputParams; } | { pathname: `/quran`; params?: Router.UnknownInputParams; } | { pathname: `/vocab`; params?: Router.UnknownInputParams; } | { pathname: `/articles/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/articles/rules/[ruleNumber]`, params: Router.UnknownInputParams & { ruleNumber: string | number; } } | { pathname: `/quran/[surahId]`, params: Router.UnknownInputParams & { surahId: string | number; } } | { pathname: `/quran/[surahId]/[ayahNumber]`, params: Router.UnknownInputParams & { surahId: string | number;ayahNumber: string | number; } } | { pathname: `/vocab/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/vocab/[id]/read`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/vocab/[id]/videos`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/vocab/[id]/watch`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/bookmarks`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/interactive`; params?: Router.UnknownOutputParams; } | { pathname: `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/articles/concepts`; params?: Router.UnknownOutputParams; } | { pathname: `/articles/method`; params?: Router.UnknownOutputParams; } | { pathname: `/articles/rules`; params?: Router.UnknownOutputParams; } | { pathname: `/quran`; params?: Router.UnknownOutputParams; } | { pathname: `/vocab`; params?: Router.UnknownOutputParams; } | { pathname: `/articles/[slug]`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `/articles/rules/[ruleNumber]`, params: Router.UnknownOutputParams & { ruleNumber: string; } } | { pathname: `/quran/[surahId]`, params: Router.UnknownOutputParams & { surahId: string; } } | { pathname: `/quran/[surahId]/[ayahNumber]`, params: Router.UnknownOutputParams & { surahId: string;ayahNumber: string; } } | { pathname: `/vocab/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/vocab/[id]/read`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/vocab/[id]/videos`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/vocab/[id]/watch`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/bookmarks${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/interactive${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/articles/concepts${`?${string}` | `#${string}` | ''}` | `/articles/method${`?${string}` | `#${string}` | ''}` | `/articles/rules${`?${string}` | `#${string}` | ''}` | `/quran${`?${string}` | `#${string}` | ''}` | `/vocab${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bookmarks`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/interactive`; params?: Router.UnknownInputParams; } | { pathname: `/menu`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/articles/concepts`; params?: Router.UnknownInputParams; } | { pathname: `/articles/method`; params?: Router.UnknownInputParams; } | { pathname: `/articles/rules`; params?: Router.UnknownInputParams; } | { pathname: `/quran`; params?: Router.UnknownInputParams; } | { pathname: `/vocab`; params?: Router.UnknownInputParams; } | `/articles/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/articles/rules/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/quran/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/quran/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/vocab/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/vocab/${Router.SingleRoutePart<T>}/read${`?${string}` | `#${string}` | ''}` | `/vocab/${Router.SingleRoutePart<T>}/videos${`?${string}` | `#${string}` | ''}` | `/vocab/${Router.SingleRoutePart<T>}/watch${`?${string}` | `#${string}` | ''}` | { pathname: `/articles/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/articles/rules/[ruleNumber]`, params: Router.UnknownInputParams & { ruleNumber: string | number; } } | { pathname: `/quran/[surahId]`, params: Router.UnknownInputParams & { surahId: string | number; } } | { pathname: `/quran/[surahId]/[ayahNumber]`, params: Router.UnknownInputParams & { surahId: string | number;ayahNumber: string | number; } } | { pathname: `/vocab/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/vocab/[id]/read`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/vocab/[id]/videos`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/vocab/[id]/watch`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
